---
- hosts: dev
  connection: ssh
  user: ansible
  become: yes

  tasks:
    - name: Install httpd based on OS
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Apache based on os
      yum:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
