[dev]
172.31.44.195
172.31.45.141

//ansible-playbook -i inventory.ini <filename.yaml> & in that plybook we need to define hosts section & /etc/ansible/ansible.cfg edit inventoy path to ini file path
